classes:{
    empty:{
        label: ""
        style: {
            fill: transparent
            stroke: transparent
        }
    }

    empty_image:{
        label: ""
        shape: image
        icon: https://icons.terrastruct.com/tech/022-server.svg
        width: 1
        height: 1
        style:{
            stroke-width: 0
            opacity: 0
        }
    }
}